### ISSUE TITLE
EBCDIC codec cp939

### ISSUE THREAD

**Issue by jaosss** [roskakori/CodecMapper#16]
Could you add the codec for cp939, please?

**Comment by roskakori** [comment]
Not easily. The currently supported codecs are all 8 bit, so adding one of these would be simple.

Cp939 seems to be a close relative of [cp930](https://en.wikipedia.org/wiki/Code_page_930), which supports 16 bit characters using some messy encoding. For this to implement, one would need test documents (both cp939 and the UTF-8 equivalent) and probably quote some time. From skimming the specs, it's rather complex bit mangling that is need to translate characters to UCS-4.

**Comment by roskakori** [comment]
Just noticed this was still lingering around and officially closed it.
