### ISSUE TITLE
Move license to LICENSE file

### ISSUE THREAD

**Issue by jayvdb** [roskakori/CodecMapper#5]
Hiya, nice solution.

Currently the pypi package for ebcdic says 'BSD', but doesnt say which BSD license, and this repo doesnt have a LICENSE file to help clarify that.

**Comment by roskakori** [comment]
Hm, there is a section "License" in the README.md that should contain all the information. Does this include all the information you are looking for?

But I can see this is a bit non standard and might be hard to find, so I might move it to a dedicated LICENSE file.

**Comment by jayvdb** [comment]
Ah, thanks, yes that is fine - sorry I didnt read it to the end.

Please do separate it out, so then GitHub will recognise it in the repo metadata, and also please include the LICENSE file in the sdist for the pypi package ebcdic.

Debian and Redhat based packaging tools also look for a `LICENSE` file, and can detect its flavour, but they dont go trying to parse a README.*.

**Comment by roskakori** [comment]
Fixed with version 1.0.1 which is now available from PyPI.

**Comment by jayvdb** [comment]
The voodoo that you put into the setup.py didnt work for me.  I needed to hack around it.  c.f.
https://build.opensuse.org/package/view_file/home:jayvdb:py-new/python-ebcdic/python-ebcdic.spec?expand=1

Typically you can declare the filename of the license file in `setup.cfg` and it will be included in the sdist and the wheel if using a modern setuptools.

**Comment by roskakori** [comment]
Darn. I wanted to avoid having two LICENSE.txt floating around in the project but of course copying them doesn't work when setup.py is executed on the target host.

So I did it the more traditional way with having a redundant file laying around in the repository but it should work now. Version 1.0.2 is already available from PyPI.

**Comment by jayvdb** [comment]
Thanks.  Submitted upstream https://build.opensuse.org/request/show/720341
